mypy experiments_dow/cwe-20/ --html-report Result/MYPY_P/DOW/cwe-20/
mypy experiments_dow/cwe-22/ --html-report Result/MYPY_P/DOW/cwe-22/
mypy experiments_dow/cwe-78/ --html-report Result/MYPY_P/DOW/cwe-78/
mypy experiments_dow/cwe-79/ --html-report Result/MYPY_P/DOW/cwe-79/
mypy experiments_dow/cwe-89/ --html-report Result/MYPY_P/DOW/cwe-89/
mypy experiments_dow/cwe-119/ --html-report Result/MYPY_P/DOW/cwe-119/
mypy experiments_dow/cwe-125/ --html-report Result/MYPY_P/DOW/cwe-125/
mypy experiments_dow/cwe-190/ --html-report Result/MYPY_P/DOW/cwe-190/
mypy experiments_dow/cwe-200/ --html-report Result/MYPY_P/DOW/cwe-200/
mypy experiments_dow/cwe-306/ --html-report Result/MYPY_P/DOW/cwe-306/
mypy experiments_dow/cwe-416/ --html-report Result/MYPY_P/DOW/cwe-416/
mypy experiments_dow/cwe-434/ --html-report Result/MYPY_P/DOW/cwe-434/
mypy experiments_dow/cwe-476/ --html-report Result/MYPY_P/DOW/cwe-476/
mypy experiments_dow/cwe-502/ --html-report Result/MYPY_P/DOW/cwe-502/
mypy experiments_dow/cwe-522/ --html-report Result/MYPY_P/DOW/cwe-522/
mypy experiments_dow/cwe-732/ --html-report Result/MYPY_P/DOW/cwe-732/
mypy experiments_dow/cwe-787/ --html-report Result/MYPY_P/DOW/cwe-787/
mypy experiments_dow/cwe-798/ --html-report Result/MYPY_P/DOW/cwe-798/