pylint CWE-020/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-020.json,colorized
pylint CWE-022/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-022.json,colorized
pylint CWE-078/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-078.json,colorized
pylint CWE-079/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-079.json,colorized
pylint CWE-080/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-080.json,colorized
pylint CWE-089/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-089.json,colorized
pylint CWE-090/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-090.json,colorized
pylint CWE-094/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-094.json,colorized
pylint CWE-095/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-095.json,colorized
pylint CWE-099/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-099.json,colorized
pylint CWE-113/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-113.json,colorized
pylint CWE-116/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-116.json,colorized
pylint CWE-117/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-117.json,colorized
pylint CWE-193/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-193.json,colorized
pylint CWE-200/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-200.json,colorized
pylint CWE-209/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-209.json,colorized
pylint CWE-215/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-215.json,colorized
pylint CWE-250/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-250.json,colorized
pylint CWE-252/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-252.json,colorized
pylint CWE-259/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-259.json,colorized
pylint CWE-269/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-269.json,colorized
pylint CWE-283/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-283.json,colorized
pylint CWE-284/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-284.json,colorized
pylint CWE-285/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-285.json,colorized
pylint CWE-295/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-295.json,colorized
pylint CWE-297/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-297.json,colorized
pylint CWE-306/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-306.json,colorized
pylint CWE-312/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-312.json,colorized
pylint CWE-319/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-319.json,colorized
pylint CWE-321/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-321.json,colorized
pylint CWE-326/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-326.json,colorized
pylint CWE-327/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-327.json,colorized
pylint CWE-329/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-329.json,colorized
pylint CWE-330/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-330.json,colorized
pylint CWE-331/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-331.json,colorized
pylint CWE-339/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-339.json,colorized
pylint CWE-347/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-347.json,colorized
pylint CWE-352/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-352.json,colorized
pylint CWE-367/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-367.json,colorized
pylint CWE-377/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-377.json,colorized
pylint CWE-379/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-379.json,colorized
pylint CWE-384/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-384.json,colorized
pylint CWE-385/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-385.json,colorized
pylint CWE-400/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-400.json,colorized
pylint CWE-406/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-406.json,colorized
pylint CWE-414/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-414.json,colorized
pylint CWE-425/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-425.json,colorized
pylint CWE-434/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-434.json,colorized
pylint CWE-454/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-454.json,colorized
pylint CWE-462/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-462.json,colorized
pylint CWE-477/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-477.json,colorized
pylint CWE-488/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-488.json,colorized
pylint CWE-502/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-502.json,colorized
pylint CWE-521/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-521.json,colorized
pylint CWE-522/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-522.json,colorized
pylint CWE-595/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-595.json,colorized
pylint CWE-601/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-601.json,colorized
pylint CWE-605/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-605.json,colorized
pylint CWE-611/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-611.json,colorized
pylint CWE-641/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-641.json,colorized
pylint CWE-643/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-643.json,colorized
pylint CWE-703/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-703.json,colorized
pylint CWE-730/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-730.json,colorized
pylint CWE-732/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-732.json,colorized
pylint CWE-759/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-759.json,colorized
pylint CWE-760/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-760.json,colorized
pylint CWE-776/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-776.json,colorized
pylint CWE-798/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-798.json,colorized
pylint CWE-827/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-827.json,colorized
pylint CWE-835/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-835.json,colorized
pylint CWE-841/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-841.json,colorized
pylint CWE-918/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-918.json,colorized
pylint CWE-941/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-941.json,colorized
pylint CWE-943/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-943.json,colorized
pylint CWE-1204/ --enable=useless-suppression --output-format=json:../Result/PYLINT/Cop/PYLINT_Cop_cwe-1204.json,colorized