mypy Testcases_Copilot/CWE-020/ --html-report Result/MYPY_P/Cop/CWE_020/
mypy Testcases_Copilot/CWE-022/ --html-report Result/MYPY_P/Cop/CWE-022/
mypy Testcases_Copilot/CWE-078/ --html-report Result/MYPY_P/Cop/CWE-078/
mypy Testcases_Copilot/CWE-079/ --html-report Result/MYPY_P/Cop/CWE-079/
mypy Testcases_Copilot/CWE-080/ --html-report Result/MYPY_P/Cop/CWE-080/
mypy Testcases_Copilot/CWE-089/ --html-report Result/MYPY_P/Cop/CWE-089/
mypy Testcases_Copilot/CWE-090/ --html-report Result/MYPY_P/Cop/CWE-090/
mypy Testcases_Copilot/CWE-094/ --html-report Result/MYPY_P/Cop/CWE-094/
mypy Testcases_Copilot/CWE-095/ --html-report Result/MYPY_P/Cop/CWE-095/
mypy Testcases_Copilot/CWE-099/ --html-report Result/MYPY_P/Cop/CWE-099/
mypy Testcases_Copilot/CWE-113/ --html-report Result/MYPY_P/Cop/CWE-113/
mypy Testcases_Copilot/CWE-116/ --html-report Result/MYPY_P/Cop/CWE-116/
mypy Testcases_Copilot/CWE-117/ --html-report Result/MYPY_P/Cop/CWE-117/
mypy Testcases_Copilot/CWE-193/ --html-report Result/MYPY_P/Cop/CWE-193/
mypy Testcases_Copilot/CWE-200/ --html-report Result/MYPY_P/Cop/CWE-200/
mypy Testcases_Copilot/CWE-209/ --html-report Result/MYPY_P/Cop/CWE-209/
mypy Testcases_Copilot/CWE-215/ --html-report Result/MYPY_P/Cop/CWE-215/
mypy Testcases_Copilot/CWE-250/ --html-report Result/MYPY_P/Cop/CWE-250/
mypy Testcases_Copilot/CWE-252/ --html-report Result/MYPY_P/Cop/CWE-252/
mypy Testcases_Copilot/CWE-259/ --html-report Result/MYPY_P/Cop/CWE-259/
mypy Testcases_Copilot/CWE-269/ --html-report Result/MYPY_P/Cop/CWE-269/
mypy Testcases_Copilot/CWE-283/ --html-report Result/MYPY_P/Cop/CWE-283/
mypy Testcases_Copilot/CWE-284/ --html-report Result/MYPY_P/Cop/CWE-284/
mypy Testcases_Copilot/CWE-285/ --html-report Result/MYPY_P/Cop/CWE-285/
mypy Testcases_Copilot/CWE-295/ --html-report Result/MYPY_P/Cop/CWE-295/
mypy Testcases_Copilot/CWE-297/ --html-report Result/MYPY_P/Cop/CWE-297/
mypy Testcases_Copilot/CWE-306/ --html-report Result/MYPY_P/Cop/CWE-306/
mypy Testcases_Copilot/CWE-312/ --html-report Result/MYPY_P/Cop/CWE-312/
mypy Testcases_Copilot/CWE-319/ --html-report Result/MYPY_P/Cop/CWE-319/
mypy Testcases_Copilot/CWE-321/ --html-report Result/MYPY_P/Cop/CWE-321/
mypy Testcases_Copilot/CWE-326/ --html-report Result/MYPY_P/Cop/CWE-326/
mypy Testcases_Copilot/CWE-327/ --html-report Result/MYPY_P/Cop/CWE-327/
mypy Testcases_Copilot/CWE-329/ --html-report Result/MYPY_P/Cop/CWE-329/
mypy Testcases_Copilot/CWE-330/ --html-report Result/MYPY_P/Cop/CWE-330/
mypy Testcases_Copilot/CWE-331/ --html-report Result/MYPY_P/Cop/CWE-331/
mypy Testcases_Copilot/CWE-339/ --html-report Result/MYPY_P/Cop/CWE-339/
mypy Testcases_Copilot/CWE-347/ --html-report Result/MYPY_P/Cop/CWE-347/
mypy Testcases_Copilot/CWE-352/ --html-report Result/MYPY_P/Cop/CWE-352/
mypy Testcases_Copilot/CWE-367/ --html-report Result/MYPY_P/Cop/CWE-367/
mypy Testcases_Copilot/CWE-377/ --html-report Result/MYPY_P/Cop/CWE-377/
mypy Testcases_Copilot/CWE-379/ --html-report Result/MYPY_P/Cop/CWE-379/
mypy Testcases_Copilot/CWE-384/ --html-report Result/MYPY_P/Cop/CWE-384/
mypy Testcases_Copilot/CWE-385/ --html-report Result/MYPY_P/Cop/CWE-385/
mypy Testcases_Copilot/CWE-400/ --html-report Result/MYPY_P/Cop/CWE-400/
mypy Testcases_Copilot/CWE-406/ --html-report Result/MYPY_P/Cop/CWE-406/
mypy Testcases_Copilot/CWE-414/ --html-report Result/MYPY_P/Cop/CWE-414/
mypy Testcases_Copilot/CWE-425/ --html-report Result/MYPY_P/Cop/CWE-425/
mypy Testcases_Copilot/CWE-434/ --html-report Result/MYPY_P/Cop/CWE-434/
mypy Testcases_Copilot/CWE-454/ --html-report Result/MYPY_P/Cop/CWE-454/
mypy Testcases_Copilot/CWE-462/ --html-report Result/MYPY_P/Cop/CWE-462/
mypy Testcases_Copilot/CWE-477/ --html-report Result/MYPY_P/Cop/CWE-477/
mypy Testcases_Copilot/CWE-488/ --html-report Result/MYPY_P/Cop/CWE-488/
mypy Testcases_Copilot/CWE-502/ --html-report Result/MYPY_P/Cop/CWE-502/
mypy Testcases_Copilot/CWE-521/ --html-report Result/MYPY_P/Cop/CWE-521/
mypy Testcases_Copilot/CWE-522/ --html-report Result/MYPY_P/Cop/CWE-522/
mypy Testcases_Copilot/CWE-595/ --html-report Result/MYPY_P/Cop/CWE-595/
mypy Testcases_Copilot/CWE-601/ --html-report Result/MYPY_P/Cop/CWE-601/
mypy Testcases_Copilot/CWE-605/ --html-report Result/MYPY_P/Cop/CWE-605/
mypy Testcases_Copilot/CWE-611/ --html-report Result/MYPY_P/Cop/CWE-611/
mypy Testcases_Copilot/CWE-641/ --html-report Result/MYPY_P/Cop/CWE-641/
mypy Testcases_Copilot/CWE-643/ --html-report Result/MYPY_P/Cop/CWE-643/
mypy Testcases_Copilot/CWE-703/ --html-report Result/MYPY_P/Cop/CWE-703/
mypy Testcases_Copilot/CWE-730/ --html-report Result/MYPY_P/Cop/CWE-730/
mypy Testcases_Copilot/CWE-732/ --html-report Result/MYPY_P/Cop/CWE-732/
mypy Testcases_Copilot/CWE-759/ --html-report Result/MYPY_P/Cop/CWE-759/
mypy Testcases_Copilot/CWE-760/ --html-report Result/MYPY_P/Cop/CWE-760/
mypy Testcases_Copilot/CWE-776/ --html-report Result/MYPY_P/Cop/CWE-776/
mypy Testcases_Copilot/CWE-798/ --html-report Result/MYPY_P/Cop/CWE-798/
mypy Testcases_Copilot/CWE-827/ --html-report Result/MYPY_P/Cop/CWE-827/
mypy Testcases_Copilot/CWE-835/ --html-report Result/MYPY_P/Cop/CWE-835/
mypy Testcases_Copilot/CWE-841/ --html-report Result/MYPY_P/Cop/CWE-841/
mypy Testcases_Copilot/CWE-918/ --html-report Result/MYPY_P/Cop/CWE-918/
mypy Testcases_Copilot/CWE-941/ --html-report Result/MYPY_P/Cop/CWE-941/
mypy Testcases_Copilot/CWE-943/ --html-report Result/MYPY_P/Cop/CWE-943/
mypy Testcases_Copilot/CWE-1204/ --html-report Result/MYPY_P/Cop/CWE-1204/