pyt Testcases_Insecure_Code/CWE-020/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-020.txt
pyt Testcases_Insecure_Code/CWE-022/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-022.txt
pyt Testcases_Insecure_Code/CWE-078/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-078.txt
pyt Testcases_Insecure_Code/CWE-079/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-079.txt
pyt Testcases_Insecure_Code/CWE-080/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-080.txt
pyt Testcases_Insecure_Code/CWE-089/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-089.txt
pyt Testcases_Insecure_Code/CWE-090/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-090.txt
pyt Testcases_Insecure_Code/CWE-094/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-094.txt
pyt Testcases_Insecure_Code/CWE-095/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-095.txt
pyt Testcases_Insecure_Code/CWE-099/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-099.txt
pyt Testcases_Insecure_Code/CWE-113/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-113.txt
pyt Testcases_Insecure_Code/CWE-116/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-116.txt
pyt Testcases_Insecure_Code/CWE-117/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-117.txt
pyt Testcases_Insecure_Code/CWE-193/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-193.txt
pyt Testcases_Insecure_Code/CWE-200/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-200.txt
pyt Testcases_Insecure_Code/CWE-209/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-209.txt
pyt Testcases_Insecure_Code/CWE-215/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-215.txt
pyt Testcases_Insecure_Code/CWE-250/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-250.txt
pyt Testcases_Insecure_Code/CWE-252/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-252.txt
pyt Testcases_Insecure_Code/CWE-259/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-259.txt
pyt Testcases_Insecure_Code/CWE-269/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-269.txt
pyt Testcases_Insecure_Code/CWE-283/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-283.txt
pyt Testcases_Insecure_Code/CWE-284/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-284.txt
pyt Testcases_Insecure_Code/CWE-285/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-285.txt
pyt Testcases_Insecure_Code/CWE-295/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-295.txt
pyt Testcases_Insecure_Code/CWE-297/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-297.txt
pyt Testcases_Insecure_Code/CWE-306/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-306.txt
pyt Testcases_Insecure_Code/CWE-312/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-312.txt
pyt Testcases_Insecure_Code/CWE-319/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-319.txt
pyt Testcases_Insecure_Code/CWE-321/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-321.txt
pyt Testcases_Insecure_Code/CWE-326/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-326.txt
pyt Testcases_Insecure_Code/CWE-327/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-327.txt
pyt Testcases_Insecure_Code/CWE-329/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-329.txt
pyt Testcases_Insecure_Code/CWE-330/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-330.txt
pyt Testcases_Insecure_Code/CWE-331/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-331.txt
pyt Testcases_Insecure_Code/CWE-339/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-339.txt
pyt Testcases_Insecure_Code/CWE-347/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-347.txt
pyt Testcases_Insecure_Code/CWE-352/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-352.txt
pyt Testcases_Insecure_Code/CWE-367/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-367.txt
pyt Testcases_Insecure_Code/CWE-377/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-377.txt
pyt Testcases_Insecure_Code/CWE-379/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-379.txt
pyt Testcases_Insecure_Code/CWE-384/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-384.txt
pyt Testcases_Insecure_Code/CWE-385/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-385.txt
pyt Testcases_Insecure_Code/CWE-400/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-400.txt
pyt Testcases_Insecure_Code/CWE-406/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-406.txt
pyt Testcases_Insecure_Code/CWE-414/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-414.txt
pyt Testcases_Insecure_Code/CWE-425/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-425.txt
pyt Testcases_Insecure_Code/CWE-434/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-434.txt
pyt Testcases_Insecure_Code/CWE-454/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-454.txt
pyt Testcases_Insecure_Code/CWE-462/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-462.txt
pyt Testcases_Insecure_Code/CWE-477/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-477.txt
pyt Testcases_Insecure_Code/CWE-488/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-488.txt
pyt Testcases_Insecure_Code/CWE-502/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-502.txt
pyt Testcases_Insecure_Code/CWE-521/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-521.txt
pyt Testcases_Insecure_Code/CWE-522/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-522.txt
pyt Testcases_Insecure_Code/CWE-595/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-595.txt
pyt Testcases_Insecure_Code/CWE-601/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-601.txt
pyt Testcases_Insecure_Code/CWE-605/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-605.txt
pyt Testcases_Insecure_Code/CWE-611/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-611.txt
pyt Testcases_Insecure_Code/CWE-641/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-641.txt
pyt Testcases_Insecure_Code/CWE-643/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-643.txt
pyt Testcases_Insecure_Code/CWE-703/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-703.txt
pyt Testcases_Insecure_Code/CWE-730/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-730.txt
pyt Testcases_Insecure_Code/CWE-732/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-732.txt
pyt Testcases_Insecure_Code/CWE-759/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-759.txt
pyt Testcases_Insecure_Code/CWE-760/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-760.txt
pyt Testcases_Insecure_Code/CWE-776/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-776.txt
pyt Testcases_Insecure_Code/CWE-798/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-798.txt
pyt Testcases_Insecure_Code/CWE-827/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-827.txt
pyt Testcases_Insecure_Code/CWE-835/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-835.txt
pyt Testcases_Insecure_Code/CWE-841/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-841.txt
pyt Testcases_Insecure_Code/CWE-918/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-918.txt
pyt Testcases_Insecure_Code/CWE-941/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-941.txt
pyt Testcases_Insecure_Code/CWE-943/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-943.txt
pyt Testcases_Insecure_Code/CWE-1204/ --output Result/PYT/Insecure_Code/PYT_InCoder_results_cwe-1204.txt