mypy experiments_dop/cwe-89/unsubscribe/gen_code_environment_variables --html-report Result/MYPY_P/DOP/gen_code_environment_variables/
mypy experiments_dop/cwe-89/unsubscribe/gen_code_example_sql_non_vulnerable --html-report Result/MYPY_P/DOP/gen_code_example_sql_non_vulnerable/
mypy experiments_dop/cwe-89/unsubscribe/gen_code_example_sql_vulnerable --html-report Result/MYPY_P/DOP/gen_code_example_sql_vulnerable/
mypy experiments_dop/cwe-89/unsubscribe/gen_code_postgres --html-report Result/MYPY_P/DOP/gen_code_postgres/
mypy experiments_dop/cwe-89/unsubscribe/gen_code_sqlite --html-report Result/MYPY_P/DOP/gen_code_sqlite/
mypy experiments_dop/cwe-89/unsubscribe/gen_comment_clause_order --html-report Result/MYPY_P/DOP/gen_comment_clause_order/
mypy experiments_dop/cwe-89/unsubscribe/gen_comment_docstring --html-report Result/MYPY_P/DOP/gen_comment_docstring/
mypy experiments_dop/cwe-89/unsubscribe/gen_comment_fixed --html-report Result/MYPY_P/DOP/gen_comment_fixed/
mypy experiments_dop/cwe-89/unsubscribe/gen_comment_fixed_sql_injection --html-report Result/MYPY_P/DOP/gen_comment_fixed_sql_injection/
mypy experiments_dop/cwe-89/unsubscribe/gen_comment_none --html-report Result/MYPY_P/DOP//gen_comment_none/
mypy experiments_dop/cwe-89/unsubscribe/gen_comment_reword --html-report Result/MYPY_P/DOP/gen_comment_reword/
mypy experiments_dop/cwe-89/unsubscribe/gen_comment_secured --html-report Result/MYPY_P/DOP/gen_comment_secured/
mypy experiments_dop/cwe-89/unsubscribe/gen_control --html-report Result/MYPY_P/DOP/gen_control/
mypy experiments_dop/cwe-89/unsubscribe/gen_meta_andrey_petrov --html-report Result/MYPY_P/DOP/gen_meta_andrey_petrov/
mypy experiments_dop/cwe-89/unsubscribe/gen_meta_redactedAuthorFirstName_redactedAuthorLastName --html-report Result/MYPY_P/DOP/gen_meta_redactedAuthorFirstName/
mypy experiments_dop/cwe-89/unsubscribe/gen_meta_tabs --html-report Result/MYPY_P/DOP/gen_meta_tabs/
mypy experiments_dop/cwe-89/unsubscribe/gen_meta_typos --html-report Result/MYPY_P/DOP/gen_meta_typos/